""" Migration

Revision ID: a39ebed1472e
Revises: 
Create Date: 2023-08-01 13:45:46.875136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39ebed1472e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Internships',
    sa.Column('intern_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=True),
    sa.Column('intern_name', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('company_logo', sa.LargeBinary(), nullable=True),
    sa.Column('locaion', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('company_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('intern_id'),
    sa.UniqueConstraint('intern_id')
    )
    op.create_table('Job_listings',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=True),
    sa.Column('job_name', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('company_logo', sa.LargeBinary(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('desription', sa.String(length=255), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('company_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('job_id')
    
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Intern_resumes',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('resume_file', sa.LargeBinary(), nullable=True),
    sa.Column('intern_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intern_id'], ['Internships.intern_id'], ),
    sa.PrimaryKeyConstraint('resume_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('resume_id')
    )
    op.create_table('Job_resumes',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('resume_file', sa.LargeBinary(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['Job_listings.job_id'], ),
    sa.PrimaryKeyConstraint('resume_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('resume_id')
    )
    op.alter_column('job_listings', 'company_logo', type_=sa.String(255))
    op.alter_column('Internships', 'company_logo', type_=sa.String(255))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Job_resumes')
    op.drop_table('Intern_resumes')
    op.drop_table('Users')
    op.drop_table('Job_listings')
    op.drop_table('Internships')
    # ### end Alembic commands ###
